apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{metadata-name}}
  namespace: {{metadata-namespace}}
  labels:
    app: {{metadata-labels-app}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{spec-selector-matchLabels-app}}
  template:
    metadata:
      labels:
        app: {{spec-template-metadata-labels-app}}
    spec:
      containers:
      - name: {{spec-template-spec-containers-name}}
        image: {{spec-template-spec-containers-image}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080