apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${TARGET_NAME}-bootstrap
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: ${TARGET_NAME}-bootstrap
    name: ${TARGET_NAME}-bootstrap
  spec:
    nodeSelector: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${BRANCH}
        uri: ${URL}
      sourceSecret:
        name: git
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - github:
        secret: 72a49182fb9b9652
      type: GitHub
    - generic:
        secret: a902eb01cc578abc
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: yaml
    labels:
      build: ${TARGET_NAME}
    name: ${TARGET_NAME}
  spec:
    lookupPolicy:
      local: false
    dockerImageRepository: "" 
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: ${TARGET_NAME}-build
    name: ${TARGET_NAME}-build
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${TARGET_NAME}:latest
    postCommit: {}
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.1
          namespace: openshift
      type: Source
  status:
    lastVersion: 
parameters:
  - name: TARGET_NAME
    displayName: Target name
    description: Target name of the application
    value: openshift Application
    required: true
  - name: URL
    displayName: URL
    description: git url
    value: https://github.com/sushpat/java-spring-boot-template-master.git
    required: true
  - name: BASE_IMAGE
    displayName: BASE_IMAGE
    description: branch of the app
    value: redhat-openjdk18-openshift:1.1
    required: true
  - name: BRANCH
    displayName: BRANCH
    description: branch of the app
    value: master
    required: true
